name: Package Project
on: [push]
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create ZIP archive
      run: zip -r tasbeeh-project.zip .
    - uses: actions/upload-artifact@v3
      with:
        name: Tasbeeh-Source-Code
        path: tasbeeh-project.zip
