name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode debug keystore
        run: base64 -d app/debug.keystore.base64 > app/debug.keystore

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew build

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk "app/build/outputs/apk/debug/مسبحة جامع عبد الرحمن بن عوف.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TasbeehApp
          path: app/build/outputs/apk/debug/
